version: '3.9'
services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
  mongodbMetaVideo:
    container_name: mongodb_meta_video_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/data-meta-video:/data/db
  mongodbNotification:
    container_name: mongodb_notification_container
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./docker-volumes/data-notification:/data/db      
  mysqlAuth:
    container_name: mysql_container
    image: mysql
    command: --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admintest
      MYSQL_DATABASE: users_auth
      MYSQL_USER: root
      MYSQL_PASSWORD: admintest
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./docker-volumes/mysql-auth:/var/lib/mysql

  postgresUser:
    container_name: postgres_user_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admintest
      POSTGRES_USER: admintest
      POSTGRES_DB: youtube_user
    ports:
      - 5433:5432
    volumes:
      - ./docker-volumes/postgresql-user:/var/lib/postgresql
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
 